services:
  manager_study:
    image: wisrovi/train_service:manager_orchestrator_v1.1.0
    restart: always
    hostname: NAS_Train_service    
    env_file:
      - control_host.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - control_network


networks:
  control_network:
    external: true
