services:
  manager_study:
    image: wisrovi/train_service:manager_orchestrator_v1.1.0
    build:
      context: ../../../wyoloservice2_manager
      dockerfile: app/Dockerfile
    restart: always
    hostname: NAS_Train_service    
    env_file:
      - control_host.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
#    volumes:
#      - /home/wisrovi/Documents/train_service_2/wyoloservice2_manager/app:/app/app
    networks:
      - control_network


networks:
  control_network:
    external: true
