services:
  fastapi:
    image: wisrovi/train_service:api_server_v1.0.0
    container_name: control_server-fastapi-1
    ports:
      - "23442:8000"
    env_file:
      - control_host.env
    restart: always
    networks:
      - control_network

networks:
  control_network:
    external: true
