services:

  mlflow:
    # use wyoloservice in postgres DB and bucket mlflow-artifacts in minio
    image: ghcr.io/mlflow/mlflow
    restart: always
    environment:
      # db
      - MLFLOW_BACKEND_STORE_URI=postgresql+psycopg2://postgres:postgres@postgres:5432/wyoloservice # Conexión a PostgreSQL
      # minio
      - MLFLOW_S3_ENDPOINT_URL=http://mlflow-minio:9000 # URL del servidor MinIO
      - AWS_ACCESS_KEY_ID=${CIFS_USER:-wisrovi} # Credenciales de MinIO
      - AWS_SECRET_ACCESS_KEY=${CIFS_PASS:-wyoloservice} # Credenciales de MinIO
      #mlflow
      - MLFLOW_TRACKING_URI=http://mlflow:5000 # URI de seguimiento de MLflow
      - MLFLOW_ARTIFACT_URI=s3://mlflow-artifacts/ # Bucket en MinIO donde se almacenarán los artefactos
    command: [ "mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "postgresql+psycopg2://postgres:postgres@postgres:5432/wyoloservice", "--default-artifact-root", "s3://mlflow-artifacts/" ]
    ports:
      - "23435:5000"
    networks:
      - control_network

  postgres:
    image: postgres:14.23
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wyoloservice
    volumes:
      - ./wyoloservice_data/postgres:/var/lib/postgresql/data
    ports:
      - "23436:5432"
    restart: always
    networks:
      - control_network

  redis:
    image: redis:8.6.3
    ports:
      - "23437:6379"
    volumes:
      - ./wyoloservice_data/cache_redis:/data
    networks:
      - control_network

  redis_commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=${CIFS_USER:-wisrovi}
      - HTTP_PASSWORD=${CIFS_PASS:-wyoloservice}
    ports:
      - "23438:8081"
    depends_on:
      - redis
    networks:
      - control_network

  mlflow-minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      - MINIO_ROOT_USER=${CIFS_USER:-wisrovi}
      - MINIO_ROOT_PASSWORD=${CIFS_PASS:-wyoloservice}
      # INDISPENSABLES PARA HABILITAR LA CONSOLA COMPLETA:
      - MINIO_SERVER_URL=http://${CONTROL_HOST:-127.0.0.1}:23439
      - MINIO_BROWSER_REDIRECT_URL=http://${CONTROL_HOST:-127.0.0.1}:23440
      # Habilitar explícitamente las características de la consola web
      - MINIO_COMPATIBILITY_MODE=edge
    ports:
      - "23439:9000"
      - "23440:9001" # web admin
    volumes:
      - ./wyoloservice_data/mlflow_minio:/data
    networks:
      - control_network

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=${REDIS_URL:-redis://redis-host:23437/0}
    ports:
      - "23441:5555"
    depends_on:
      - redis
    extra_hosts:
      - "redis-host:host-gateway"
    networks:
      - control_network
      
  sambas:
    image: dperson/samba
    environment:
      - TZ=Europe/Madrid
      - USERID=1000
      - GROUPID=1000
      - SAMBA_USERS=${CIFS_USER:-wisrovi};${CIFS_PASS:-wyoloservice}
    volumes:
      - ./datasets/datasets:/data/datasets
      - ./datasets/config_models:/data/config_versions
      - ./datasets/db:/data/api_database
    restart: always
    command: >
      -u "admin_deployd;qoyaJYuFVsGvLOlz45Ad"
      -s "datasets;/data/datasets;yes;no;yes;all"
      -s "config_versions;/data/config_versions;yes;no;yes;all"
      -s "api_database;/data/api_database;yes;no;yes;all"
    ports:
      - "23449:445/tcp" # SMB over TCP
    networks:
      - control_network

  optuna_official_dashboard:
    # use optuna_db in postgres DB
    image: wisrovi/train_service:optuna_dashboard_v1.0.0
    restart: always
    ports:
      - "23443:8080"
    networks:
      - control_network

networks:
  control_network:
    external: true
